In [25]:
# vaiable 1 : Smart Thermostats vs. Smart Lights
# variable 2 : Satisfaction(Very Satisfied,Satisfied,Neutral,Unsatisfied,Very Unsatisfied)

# test alpha value
alpha = 0.05

# h0 : satisfaction and item bought are two independent (no associantion)
# h1 : satisfaction and item bought are two not independent (there is associantion)

# caluculate the expencted values 
 # E = (row_total * col_total)/ Grand total


In [2]:
import numpy as np
import scipy.stats as stats

In [3]:
observed = np.array([
    [50,70],
    [80,100],
    [60,90],
    [30,50],
    [20,50]
])

In [15]:
row_total = observed.sum(axis=1)
print(row_total)

[120 180 150  80  70]


In [16]:
col_total = observed.sum(axis =0)
print(col_total)

[240 360]


In [17]:
grand_total = observed.sum()
print(grand_total)

600


In [19]:
# find the expected values
expected = np.outer(row_total , col_total) / grand_total
print(expected)

[[ 48.  72.]
 [ 72. 108.]
 [ 60.  90.]
 [ 32.  48.]
 [ 28.  42.]]


In [20]:
# chi sqauare statictic


In [21]:
chi_square = ((observed - expected)**2/expected).sum()

In [22]:
print(chi_square)

5.638227513227513


In [23]:
# dergees of freedom 
dof = (observed.shape[0]-1) * (observed.shape[1]-1)
print(dof)

4


In [24]:
# p value 
p_value = 1 - stats.chi2.cdf(chi_square , dof)
print(p_value)

0.22784371130697179


In [27]:
if p_value > alpha :
    print( "fail to reject h0 : ther is no association between them")
else:
    print("fail to reject h1 : ther is association between them")

fail to reject h0 : ther is no association between them


In [29]:
# method 2 shotcut
chi2 , p_value2 , dof2,expected2 = stats.chi2_contingency(observed)

In [30]:
print( chi2)
print( p_value2)
print( dof2)
print( expected2)
# same as the above 

5.638227513227513
0.22784371130697176
4
[[ 48.  72.]
 [ 72. 108.]
 [ 60.  90.]
 [ 32.  48.]
 [ 28.  42.]]


In [31]:
if p_value2 > alpha :
    print( "fail to reject h0 : ther is no association between them")
else:
    print("reject h0 : ther is association between them")

fail to reject h0 : ther is no association between them


In [32]:
# comparing it with the critical value 
critical_value = stats.chi2.ppf(1 - alpha, dof)
print(critical_value)  # ≈ 9.4877 for dof=4, alpha=0.05

9.487729036781154


In [33]:
if chi_square > critical_value :
    print('reject h0')
else:
    print('fail to reject h0')

fail to reject h0
