Univariate Selection


In [4]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# Load data

filename = '/Users/furkhanansari/Desktop/Data Science/DataSets/pima-indians-diabetes.data.csv'
name = ['preg' , 'plas' , 'pres' ,'skin' , 'test', 'mass','pedi' , 'age','class']
dataframe = read_csv(filename , names = name)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

#feature extraction 
test = SelectKBest(score_func = chi2 , k =4)
fit = test.fit(X,Y)

# summarize scores
set_printoptions(precision = 3)
print(name)
print(fit.scores_)
features = fit.transform(X)

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


Recursive Feature selection

In [12]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# Load data

filename = '/Users/furkhanansari/Desktop/Data Science/DataSets/pima-indians-diabetes.data.csv'
name = ['preg' , 'plas' , 'pres' ,'skin' , 'test', 'mass','pedi' , 'age','class']
dataframe = read_csv(filename , names = name)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

#feature extraction 
model = LogisticRegression(max_iter = 400)
rfe = RFE(estimator=model, n_features_to_select=3)
fit = rfe.fit(X,Y)


In [13]:
# Num Features : 
fit.n_features_

np.int64(3)

In [14]:
# Selected Features :
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [15]:
# feature Ranking
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

Feature importance using decision tree





In [17]:
# Feature Importance with Extra Tree Classifier
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier

# load data
filename = '/Users/furkhanansari/Desktop/Data Science/DataSets/pima-indians-diabetes.data.csv'
name = ['preg' , 'plas' , 'pres' ,'skin' , 'test', 'mass','pedi' , 'age','class']
dataframe = read_csv(filename , names = name)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

# feature extraction
model = DecisionTreeClassifier()
model.fit(X,Y)
print(model.feature_importances_)

[0.06  0.327 0.093 0.019 0.03  0.226 0.128 0.116]
